Fundamentals/C# Fundamentals - May 2024/Basic Web Project/AspNetCoreDemo/AspNetCoreWebApp/Models/Course.cs
namespace DemoWebApp.Models
{
    public class Course
    {
        public Course(string name)
        {
            this.Name = name;
        }
        public string Name { get; set; }
    }
}

Fundamentals/C# Fundamentals - May 2024/Basic Web Project/AspNetCoreDemo/AspNetCoreWebApp/Models/Courses.cs
namespace DemoWebApp.Models
{
    public class Courses
    {
        public List<Course> GetCourses()
        {
            List<Course> courses = new List<Course>();

            for(int i = 1; i <= 100; i++)
            {
                courses.Add(new Course($"Course {i}"));
            }

            return courses;
        }
    }
}

Fundamentals/C# Fundamentals - May 2024/Basic Web Project/AspNetCoreDemo/AspNetCoreWebApp/Controllers/HomeController.cs
using DemoWebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace DemoWebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            Courses coursesDatabase = new Courses();

            List<Course> courses = coursesDatabase.GetCourses();

            return View(courses);
        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

Fundamentals/C# Fundamentals - May 2024/Basic Web Project/AspNetCoreDemo/AspNetCoreWebApp/Controllers/NumbersController.cs
using Microsoft.AspNetCore.Mvc;

namespace DemoWebApp.Controllers
{
    public class NumbersController : Controller
    {
        public IActionResult NumbersFrom1ToN(int number)
        {
            return View(number);
        }
    }
}

Fundamentals/C# Fundamentals - May 2024/Basic Web Project/AspNetCoreDemo/AspNetCoreWebApp/Views/Home/Index.cshtml
@using DemoWebApp.Models

@model List<Course>

@foreach (Course course in Model)
{
    <p>@course.Name</p>
}

Fundamentals/C# Fundamentals - May 2024/Basic Web Project/AspNetCoreDemo/AspNetCoreWebApp/Views/Numbers/NumbersFrom1ToN.cshtml
@model int

<h1>Numbers should be displayed here!</h1>

<form method="post">
    <input type="number" name="number" />
    <button type="submit">Submit</button>
</form>

<div id="txt"></div>

@for(int i = 1; i <= Model; i++)
{
    <div>@i</div>
}

Fundamentals/C# Fundamentals - May 2024/Basic Web Project/AspNetCoreDemo/AspNetCoreWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DemoWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DemoWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DemoWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Numbers" asp-action="NumbersFrom1ToN">NumbersFrom1ToN</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DemoWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>